import type { Metadata } from "next";
import { Inter, Poppins, Lexend } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const lexend = Lexend({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: "100",
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "LP Whitelabel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lexend.variable} ${poppins.variable}`}>
      <head></head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
