import type { Metadata } from "next";
import { lexend, poppins, inter } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "LP Whitelabel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${lexend.variable} ${poppins.variable}`}>
        {children}
      </body>
    </html>
  );
}
